### ISSUE TITLE
"status message should be OK, found: Success"

### ISSUE THREAD

**Issue by avidrissman** [nmrshll/gphotos-uploader-cli#64] opened 2019-06-15 21:47 UTC
(FYI, I'm using rfgamaral/docker-gphotos-uploader who wraps this.)

This has been working great for me, but when I tried today I got:

> 2019/06/15 21:44:28 Uploading HQXS2530.JPG
> 2019/06/15 21:44:30 failed uploading image
>  --- at /go/src/github.com/nmrshll/gphotos-uploader-cli/upload/fileUpload.go:33 (StartFileUploadWorker.func1) ---
> Caused by: failed uploading image
>  --- at /go/src/github.com/nmrshll/gphotos-uploader-cli/upload/fileUpload.go:53 (FileUpload.upload) ---
> Caused by: status message should be OK, found: Success
>  --- at /go/src/github.com/nmrshll/google-photos-api-client-go/lib-gphotos/client.go:147 (Client.UploadFile) ---

Is there a recent change to the Photos API?

**Comment by amatmv** [comment] 2019-06-18 18:47
Same problem here... just suddenly happening.

**Comment by brett-w-thompson** [comment] 2019-06-25 01:57
I modified line 123 in `client.go` to be:

	if result.Status.Message != "OK" && result.Status.Message != "Success" {

which fixed it. I think to fix it properly someone would need to submit a PR over to `lib-gphotos` (https://github.com/nmrshll/google-photos-api-client-go/tree/master/lib-gphotos I think)

**Comment by softcoder** [comment] 2019-06-25 14:41
How do you recompile this project to get a new binary locally?

**Comment by pacoorozco** [comment] 2019-06-25 15:49
HiThere are some instructions on the projects Readme. But it can be summarized by clone and makePacoEl 25 jun. 2019 16:42, Mark Vejvoda <notifications@github.com> escribió:How do you recompile this project to get a new binary locally?

**Comment by softcoder** [comment] 2019-06-25 23:28
After applying the fix it works for a few more images then i get an error just like this: https://github.com/google/data-transfer-project/issues/651

Shows up in my console as (hid my project info with XX):

2019/06/25 16:27:29 Uploading img_2615.jpg
2019/06/25 16:27:32 failed uploading image: failed uploading image: failed adding media img_2613.jpg
 --- at /home/softcoder/go/pkg/mod/github.com/nmrshll/google-photos-api-client-go@v0.0.0-20180906090521-a94d2fbcfb40/lib-gphotos/client.go:115 (Client.UploadFile) ---
Caused by: googleapi: Error 429: Quota exceeded for quota metric 'photoslibrary.googleapis.com/write_requests' and limit 'WritesPerMinutePerUser' of service 'photoslibrary.googleapis.com' for consumer 'project_number:XX'., rateLimitExceeded

**Comment by pacoorozco** [comment] 2019-07-01 14:59
Hi

I've asked @nmrshll to have write permission to fix the issue. we can hopefully solve it soon

**Comment by rfgamaral** [comment] 2019-07-06 17:25
@pacoorozco I see that you release v0.3.0 a few days ago. Is that build supposed to be working without [merging this first](https://github.com/nmrshll/google-photos-api-client-go/pull/9)?

**Comment by pacoorozco** [comment] 2019-07-08 06:58
Not sure... I've tested it and it works on my side, but I think it could not work on other environments... @nmrshll has not answered me.. yet

**Comment by pacoorozco** [comment] 2019-07-08 15:14
Hi @rfgamaral 

I've forked the parent repo: https://github.com/gphotosuploader/google-photos-api-client-go

And fixed the issue, so this should solve the problem using `gphotos-uploader-cli`.

Can you confirm it?

**Comment by rfgamaral** [comment] 2019-07-08 15:20
I can't do that confirmation for you because I'm not currently using `gphotos-uploader-cli` (but I'm trying to maintain my Docker image) and this was an issue some people complained on my repository. I just noticed you've been releasing new versions without that extra condition and was wondering why it was working without it.

I hope this is a temporary fix and I hope @nmrshll can you give you collaborator access to the original repo so we don't start forking everything just to fix tiny bugs, it will be much harder to keep track and maintain these projects like that :/

**Comment by Brimstedt** [comment] 2019-07-08 20:47
a temporary fix if you dont mind compiling gphotos-uploader-cli yourself is to change the logging from Fatal to Print.
upload/fileUpload.go, line 34

(and you dont need to fork the repo, just clone it locally)

**Comment by qwandor** [comment] 2019-07-09 20:27
I'm seeing this issue in the latest release v0.3.1 still.

**Comment by pacoorozco** [comment] 2019-07-10 06:20
Hi @qwandor 

There are different issues mentioned in this thread :sweat: **Which one is the one you are seeing?** 

Can you paste the log, please?

Paco

**Comment by ivanorJunior** [comment] 2019-07-11 12:45
`gphotos-uploader-cli$ ./gphotos-uploader-cli
2019/07/11 08:03:21 album not created: /media/ivanor/Seagate Expansion Drive/sim/ivanor/Imagens/Chapada_solo. set jobs.makeAlbums.enabled = true to create albums
2019/07/11 08:03:21 Uploading image01317.jpg
2019/07/11 08:03:21 Uploading image01318.jpg
2019/07/11 08:03:21 Uploading image01319.jpg
2019/07/11 08:03:21 Uploading image01320.jpg
2019/07/11 08:03:21 Uploading image01321.jpg
2019/07/11 08:11:03 failed uploading image: failed uploading image: status message should be OK, found: Success
 --- at /home/ivanor/go/src/github.com/nmrshll/google-photos-api-client-go/lib-gphotos/client.go:147 (Client.UploadFile) ---
`

**Comment by pacoorozco** [comment] 2019-07-11 13:46
Sorry, I didn't update the dependencies version. It should be fixed by #85, so let's try v0.3.2

**Closed by pacoorozco** 2019-07-11 13:46 UTC

**Comment by ivanorJunior** [comment] 2019-07-11 14:00
> I modified line 123 in `client.go` to be:
> 
> ```
> if result.Status.Message != "OK" && result.Status.Message != "Success" {
> ```
> 
> which fixed it. I think to fix it properly someone would need to submit a PR over to `lib-gphotos` (https://github.com/nmrshll/google-photos-api-client-go/tree/master/lib-gphotos I think)

Ok. That worked for me. Thanks.
